# -*- coding: utf-8 -*-
"""task2_9_extra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haQH67t8oXPb-PzsyxVoPaKwBUm9rq8P
"""

желание = input("Что вы хотели бы купить: ")

print(f"Ваша покупка '{желание}' будет выполнена")